# 新闻源配置文件
# 支持通过配置文件动态配置新闻源

# 默认新闻源配置（只保留华尔街见闻）
default_sources:
  - name: "华尔街见闻"
    routes:
      - route: "wallstreetcn/news/global"
        category: "全球财经"
      - route: "wallstreetcn/news/domestic"
        category: "国内财经"

# 可选的新闻源配置
optional_sources:
  - name: "中国新闻网"
    routes:
      - route: "chinanews"
        category: "国内要闻"
  - name: "商业-封面新闻"
    routes:
      - route: "thecover/channel/4"
        category: "商业资讯"
  - name: "深圳本地宝焦点资讯"
    routes:
      - route: "bendibao/news/sz"
        category: "深圳本地"
  - name: "澎湃新闻-首页头条"
    routes:
      - route: "thepaper/featured"
        category: "头条新闻"
  - name: "CCTV新闻联播"
    routes:
      - route: "cctv/xwlb"
        category: "时政要闻"
  - name: "极客日报"
    routes:
      - route: "csdn/blog/csdngeeknews"
        category: "科技资讯"
  - name: "Artificial-intelligence"
    routes:
      - route: "topic/artificial-intelligence/feed/"
        category: "人工智能"
  - name: "财经频道"
    routes:
      - route: "rss/finance.xml"
        category: "财经快讯"
  - name: "TechWeb每日热点"
    routes:
      - route: "rss/hotnews"
        category: "科技热点"
  - name: "每日环球视野"
    routes:
      - route: "idaily/today"
        category: "国际新闻"
  - name: "TheBlockBeats-快讯"
    routes:
      - route: "theblockbeats/newsflash/0"
        category: "区块链快讯"
  - name: "7x24小时快讯"
    routes:
      - route: "fx678/kx"
        category: "外汇快讯"
  - name: "财富中文网"
    routes:
      - route: "fortunechina"
        category: "财富资讯"
  - name: "百度热搜"
    routes:
      - route: "baidu/top"
        category: "热搜榜单"
  - name: "格隆汇快讯"
    routes:
      - route: "gelonghui/live"
        category: "市场快讯"
  - name: "今日热门"
    routes:
      - route: "coolapk/hot"
        category: "热门资讯"
  - name: "第一财经"
    routes:
      - route: "yicai/latest"
        category: "财经动态"
  - name: "AI新闻资讯"
    routes:
      - route: "aibase/news"
        category: "AI动态"
  - name: "雪球"
    routes:
      - route: "xueqiu/timeline/a"
        category: "沪深市场"
      - route: "xueqiu/timeline/hk"
        category: "港股市场"
      - route: "xueqiu/timeline/us"
        category: "美股市场"
      - route: "xueqiu/hots"
        category: "热门话题"
  - name: "东方财富"
    routes:
      - route: "eastmoney/roll"
        category: "滚动新闻"
      - route: "eastmoney/gg"
        category: "公告新闻"
      - route: "eastmoney/kx"
        category: "快讯新闻"
  - name: "财新"
    routes:
      - route: "caixin/finance"
        category: "财经新闻"
      - route: "caixin/stock"
        category: "股票新闻"
      - route: "caixin/fund"
        category: "基金新闻"

# 启用的新闻源列表（从可选新闻源中选择启用）
enabled_sources:
  - "华尔街见闻"
  - "AI新闻资讯"
  - "第一财经"
  - "今日热门"
  - "格隆汇快讯"
  - "百度热搜"
  - "财富中文网"
  - "7x24小时快讯"
  - "TheBlockBeats-快讯"
  - "每日环球视野"
  # - "TechWeb每日热点"
  # - "财经频道"
  # - "Artificial-intelligence"
  - "极客日报"
  - "CCTV新闻联播"
  - "澎湃新闻-首页头条"
  - "深圳本地宝焦点资讯"
  - "商业-封面新闻"
  - "中国新闻网"